"""CLI entry: drive the pipeline orchestrator from a YAML config.

Usage:
    python -m ttsd.runners.pipeline.run_pipeline \
        --config configs/pipeline/noop_smoke.yaml \
        --prompt "a person swimming in ocean" \
        --seed 0
"""

from __future__ import annotations

import argparse
import datetime as dt
from pathlib import Path

from ttsd.pipeline import Orchestrator, load_config


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--config", required=True, type=Path)
    p.add_argument("--prompt", required=True, type=str)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--run-id", type=str, default=None,
                   help="Override autogenerated timestamp run-id.")
    args = p.parse_args(argv)

    cfg = load_config(args.config)
    orch = Orchestrator(cfg)
    run_id = args.run_id or dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    print(f"[pipeline] run_id={run_id}")
    print(f"[pipeline] config={args.config}")
    print(f"[pipeline] prompt='{args.prompt}'  seed={args.seed}")
    result = orch.run(prompt=args.prompt, seed=args.seed, run_id=run_id)
    print()
    print(f"[pipeline] success={result.success}")
    print(f"[pipeline] video={result.video_path}")
    print(f"[pipeline] events={result.events_path}")
    print(f"[pipeline] final_score={result.final_score}")
    print(f"[pipeline] trials={result.n_trials} terminating={result.terminating_trial}")


if __name__ == "__main__":
    main()
