"""Phase 0 baseline runner.

Generates a sweep of (prompt × seed) clips on Wan 2.2 5B at 480p, persisting
intermediate latents at every-N-steps for the Phase 1 verifier.

Headline artifact: per-prompt VBench-score variance across seeds → the
TTS-necessity argument for the rest of the project.

Usage:
    python -m ttsd.runners.baseline --config configs/baseline_wan22_480p.yaml
    python -m ttsd.runners.baseline --config configs/baseline_wan22_480p.yaml --smoke
"""

from __future__ import annotations

import argparse
import datetime as dt
import importlib
import json
import os
from dataclasses import asdict, dataclass
from pathlib import Path

import torch
import yaml


@dataclass
class RunMeta:
    prompt_id: str
    prompt_text: str
    axis: str
    seed: int
    model: str
    height: int
    width: int
    num_frames: int
    num_inference_steps: int
    guidance_scale: float
    snapshot_steps: list[int]
    timestamp: str
    capture_posterior_means: bool = False
    posterior_mean_steps: list[int] | None = None
    scheduler: str = "unipc"


def _load_prompts(spec: str) -> list[dict]:
    module_path, attr = spec.split(":")
    module = importlib.import_module(module_path)
    return getattr(module, attr)


def _save_video(frames, path: Path, fps: int = 16) -> None:
    import imageio.v3 as iio
    import numpy as np

    # Normalize to uint8 H×W×3.
    arr = frames if hasattr(frames, "__array__") else frames.cpu().numpy()
    arr = np.asarray(arr)
    if arr.dtype != np.uint8:
        arr = (arr.clip(0.0, 1.0) * 255).astype("uint8")
    if arr.ndim == 4 and arr.shape[-1] != 3 and arr.shape[1] == 3:
        arr = arr.transpose(0, 2, 3, 1)
    iio.imwrite(path, arr, fps=fps, codec="libx264")


def _snapshot_step_indices(num_steps: int, every_n: int, also_keep: list[int]) -> list[int]:
    s = set(range(every_n - 1, num_steps, every_n))
    s.update(i for i in also_keep if 0 <= i < num_steps)
    return sorted(s)


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--config", required=True, type=Path)
    p.add_argument("--smoke", action="store_true", help="One prompt, one seed — sanity check.")
    p.add_argument("--limit-prompts", type=int, default=None)
    p.add_argument("--limit-seeds", type=int, default=None)
    p.add_argument(
        "--capture-posterior-means",
        dest="capture_posterior_means",
        action="store_true",
        default=None,
        help="Also save the scheduler's predicted clean sample (Tweedie / x0_hat) "
             "at each snapshot step into <seed>/posterior_means/. Overrides config.",
    )
    p.add_argument(
        "--no-capture-posterior-means",
        dest="capture_posterior_means",
        action="store_false",
        help="Disable posterior-mean capture even if the config enables it.",
    )
    p.add_argument(
        "--run-id", type=str, default=None,
        help="Override the autogenerated timestamp run-id. Lets multiple shards "
             "write into the same run directory.",
    )
    p.add_argument(
        "--shard-index", type=int, default=0,
        help="This worker's shard index in [0, --num-shards). The full work list "
             "is flattened to (prompt, seed) pairs in a stable order, and each "
             "worker processes the pairs where (i %% num_shards) == shard_index. "
             "Combined with the DONE marker, this is safe to resume.",
    )
    p.add_argument(
        "--num-shards", type=int, default=1,
        help="Total number of shards (workers) cooperatively processing the "
             "same run-id. Default 1 = no sharding.",
    )
    args = p.parse_args(argv)
    if not (0 <= args.shard_index < args.num_shards):
        raise SystemExit(
            f"--shard-index {args.shard_index} out of range for --num-shards {args.num_shards}"
        )

    cfg = yaml.safe_load(args.config.read_text())

    # Lazy import so --help works even if torch/diffusers aren't installed.
    from ttsd.models.wan22_adapter import Wan22Adapter

    model_cfg = cfg["model"]
    gen_cfg = cfg["generation"]
    snap_cfg = cfg["snapshots"]
    out_cfg = cfg["output"]

    dtype = {"bf16": torch.bfloat16, "fp16": torch.float16, "fp32": torch.float32}[model_cfg["dtype"]]
    scheduler_kind = model_cfg.get("scheduler", "unipc")
    adapter = Wan22Adapter(
        model_path=model_cfg["path"],
        dtype=dtype,
        device=model_cfg["device"],
        scheduler_kind=scheduler_kind,
    )

    prompts = _load_prompts(cfg["prompts"]["source"])
    default_seeds = [cfg["seeds"]["base"] + i for i in range(cfg["seeds"]["count"])]

    if args.smoke:
        prompts = prompts[:1]
        default_seeds = default_seeds[:1]
    if args.limit_prompts:
        prompts = prompts[: args.limit_prompts]

    # Flatten to (prompt, seed) pairs in a stable order. Per-prompt `seeds`
    # override the global default; smoke / --limit-seeds still apply on top.
    work: list[tuple[dict, int]] = []
    for prompt in prompts:
        seeds_for_prompt = prompt.get("seeds") or default_seeds
        if args.smoke:
            seeds_for_prompt = seeds_for_prompt[:1]
        if args.limit_seeds:
            seeds_for_prompt = seeds_for_prompt[: args.limit_seeds]
        for seed in seeds_for_prompt:
            work.append((prompt, int(seed)))

    # Shard across cooperating workers (typically one per GPU). All workers
    # must see the same `work` list (i.e., same config + prompts module).
    total_clips = len(work)
    if args.num_shards > 1:
        work = [pair for i, pair in enumerate(work) if i % args.num_shards == args.shard_index]

    snapshot_steps = _snapshot_step_indices(
        gen_cfg["num_inference_steps"],
        snap_cfg["every_n_steps"],
        snap_cfg.get("also_keep", []),
    )

    # Resolve posterior-mean capture: CLI overrides config; default off.
    if args.capture_posterior_means is None:
        capture_posterior_means = bool(snap_cfg.get("posterior_means", False))
    else:
        capture_posterior_means = bool(args.capture_posterior_means)
    posterior_mean_steps = snapshot_steps if capture_posterior_means else []

    # Exp 0 / TT-FMD: also capture pre-step latents (z_i) and raw model outputs (o_i).
    capture_raw_latents = bool(snap_cfg.get("capture_raw_latents", False))
    raw_latent_steps = snapshot_steps if capture_raw_latents else []
    model_output_steps = snapshot_steps if capture_raw_latents else []

    run_id = args.run_id or out_cfg.get("run_id") or dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    run_root = Path(out_cfg["root"]) / run_id
    run_root.mkdir(parents=True, exist_ok=True)
    # Only the first writer fills config.snapshot.yaml — avoids 4 shards
    # racing to write the same file.
    snap_path = run_root / "config.snapshot.yaml"
    if not snap_path.exists():
        snap_path.write_text(yaml.safe_dump(cfg))

    print(f"[baseline] run_root={run_root}")
    shard_tag = f" (shard {args.shard_index}/{args.num_shards})" if args.num_shards > 1 else ""
    print(f"[baseline] total clips across all shards: {total_clips}; this shard: {len(work)}{shard_tag}")
    print(f"[baseline] snapshotting steps: {snapshot_steps}")
    print(f"[baseline] capture posterior means: {capture_posterior_means}")
    print(f"[baseline] scheduler: {scheduler_kind}")

    height, width = gen_cfg["resolution"]

    for prompt, seed in work:
        out_dir = run_root / prompt["id"] / f"seed{seed:04d}"
        if (out_dir / "DONE").exists():
            print(f"[baseline] SKIP {prompt['id']} seed={seed} (already done)")
            continue
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "latents").mkdir(exist_ok=True)
        if capture_posterior_means:
            (out_dir / "posterior_means").mkdir(exist_ok=True)
        if capture_raw_latents:
            (out_dir / "raw_latents").mkdir(exist_ok=True)
            (out_dir / "model_outputs").mkdir(exist_ok=True)

        print(f"[baseline] ▶ {prompt['id']} seed={seed} :: {prompt['text'][:60]}…")
        if capture_posterior_means or capture_raw_latents:
            result = adapter.generate_with_posterior_means(
                prompt=prompt["text"],
                seed=seed,
                num_frames=gen_cfg["num_frames"],
                height=height,
                width=width,
                num_inference_steps=gen_cfg["num_inference_steps"],
                guidance_scale=gen_cfg["guidance_scale"],
                snapshot_steps=snapshot_steps,
                posterior_mean_steps=posterior_mean_steps,
                raw_latent_steps=raw_latent_steps,
                model_output_steps=model_output_steps,
            )
        else:
            result = adapter.generate(
                prompt=prompt["text"],
                seed=seed,
                num_frames=gen_cfg["num_frames"],
                height=height,
                width=width,
                num_inference_steps=gen_cfg["num_inference_steps"],
                guidance_scale=gen_cfg["guidance_scale"],
                snapshot_steps=snapshot_steps,
            )

        if out_cfg.get("save_video", True):
            _save_video(result.frames, out_dir / "video.mp4")
        if out_cfg.get("save_latents", True):
            for step_idx, latent in result.latents_by_step.items():
                torch.save(latent, out_dir / "latents" / f"step_{step_idx:03d}.pt")
        if capture_posterior_means:
            for step_idx, posterior in result.posterior_means_by_step.items():
                torch.save(posterior, out_dir / "posterior_means" / f"step_{step_idx:03d}.pt")
        if capture_raw_latents:
            for step_idx, raw in result.raw_latents_by_step.items():
                torch.save(raw, out_dir / "raw_latents" / f"step_{step_idx:03d}.pt")
            for step_idx, mo in result.model_outputs_by_step.items():
                torch.save(mo, out_dir / "model_outputs" / f"step_{step_idx:03d}.pt")
            if result.scheduler_meta:
                (out_dir / "scheduler_meta.json").write_text(
                    json.dumps(result.scheduler_meta, indent=2)
                )

        meta = RunMeta(
            prompt_id=prompt["id"],
            prompt_text=prompt["text"],
            axis=prompt.get("axis", ""),
            seed=seed,
            model=model_cfg["name"],
            height=height,
            width=width,
            num_frames=gen_cfg["num_frames"],
            num_inference_steps=gen_cfg["num_inference_steps"],
            guidance_scale=gen_cfg["guidance_scale"],
            snapshot_steps=snapshot_steps,
            timestamp=dt.datetime.now().isoformat(timespec="seconds"),
            capture_posterior_means=capture_posterior_means,
            posterior_mean_steps=posterior_mean_steps if capture_posterior_means else None,
            scheduler=scheduler_kind,
        )
        (out_dir / "meta.json").write_text(json.dumps(asdict(meta), indent=2))
        (out_dir / "DONE").touch()

    print(f"[baseline] done. outputs under {run_root}")


if __name__ == "__main__":
    main()
